### ISSUE TITLE
[FEATURE REQUEST] Ability to set environment name

### ISSUE THREAD

**Issue by yogendra** [YugabyteDB-Samples/yb-workload-simulator#18]
I have used this app for demonstrating intel v/s graviton performance. It would be good to have an environment name identifier supplied to the app and shows in the UI. May be we can use application.name attribute from spring config.

**Comment by akscjo** [comment]
@yogendra Issue has been fixed. You can set the environment variable and UI will show that up (please see screenshot). For example,
export SPRING_APPLICATION_NAME=GRAVITON
<img width="457" alt="Screenshot 2023-06-21 at 3 20 55 PM" src="https://github.com/YugabyteDB-Samples/yb-workload-simulator/assets/92008321/6216fbfe-a363-4ba8-ac17-522680b37cfb">

Fix will be available in v0.0.7+
